apiVersion: quay.redhat.com/v1
kind: QuayRegistry
metadata:
  name: quay-registry
  namespace: quay-enterprise
spec:
  configBundleSecret: quay-config-bundle
  components:
    - kind: horizontalpodautoscaler
      managed: false
    - kind: objectstorage
      managed: false
