apiVersion: v1
stringData:
  config.yaml: |
    DISTRIBUTED_STORAGE_CONFIG:
      default:
        - RHOCSStorage
        - hostname: {{ .Values.objectStorage.hostname }}
          access_key: {{ .Values.objectStorage.accessKey }}
          secret_key: {{ .Values.objectStorage.secretAccessKey }}
          bucket_name: {{ .Values.objectStorage.bucketName }}
          port: "{{ .Values.objectStorage.port }}"
          is_secure: {{ .Values.objectStorage.isSecure }}
          storage_path: /datastorage/registry
    DISTRIBUTED_STORAGE_DEFAULT_LOCATIONS: []
    DISTRIBUTED_STORAGE_PREFERENCE:
      - default
kind: Secret
metadata:
  name: quay-config-bundle
  namespace: quay-enterprise
type: Opaque
